version: '2'

services:
  jekyll:
    image: wyliog/jekyll:v3.7.3
    # command: sleep 3600
    command: jekyll serve --watch --force_polling --verbose
    # - /bin/bash 
    # - -c 
    # - |
    #   cd /srv/jekyll
    #   bundle update
    #   jekyll serve --watch --force_polling --verbose
    ports:
      - 4000:4000
    volumes:
      - ./:/srv/jekyll
